# Generated by Django 3.0.6 on 2020-05-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='source_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
